### Get all Employees Details
GET http://localhost:4004/odata/v4/employee/Employees


### Get all Employee details expanded with Profile
GET http://localhost:4004/odata/v4/employee/Employees?$expand=profile


### Get Employee by ID expanded with Profile
GET http://localhost:4004/odata/v4/employee/Employees(ID='d669869b-d4fa-4e1b-a669-6bd04ff71677')?$expand=profile


### Create Employee
POST http://localhost:4004/odata/v4/employee/Employees
Content-Type: application/json

{
    "name": "Vikash Patel",
    "email": "vikash.patel@example.com",
    "organization": {
            "ID" : "ORG002"
        },
    "profile": {
        "phoneNumber": "123-456-7890",
        "address": "123 Main St, City, State 12345",
        "dateOfBirth": "1990-01-01"
    }  
}



### Get Employee Profile Details
GET http://localhost:4004/odata/v4/employee/EmployeeProfiles



### Get Employee Profile Details
GET http://localhost:4004/odata/v4/employee/EmployeeProfiles('69b4e0e3-2e44-4b35-9c69-deef58d0a056')