### Get Warehouse by ID with Path Parameter
GET http://localhost:4004/odata/v4/warehouse/Warehouses(550e8400-e29b-41d4-a716-446655440009)
Content-Type: application/json


### Get Warehouse by ID with Path Parameter
GET http://localhost:4004/odata/v4/warehouse/Warehouses(ID=550e8400-e29b-41d4-a716-446655440008)
Content-Type: application/json


### Get Warehouses ID and name using Query Parameters $select
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$select=ID,name
Content-Type: application/json


### Get Warehouses with name containing 'Warehouse' using Query Parameters $search
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$search=Warehouse
Content-Type: application/json


### Get Warehouses with name equal to 'Elite Storage' using Query Parameters $filter
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$filter=name eq 'Elite Storage'
Content-Type: application/json


### Get Warehouses with ID greater than specified using Query Parameters $filter
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$filter=ID gt 550e8400-e29b-41d4-a716-446655440004
Content-Type: application/json


### Get Warehouses with ID greater than specified and name equal to 'Elite Storage' using Query Parameters $filter
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$filter=ID gt 550e8400-e29b-41d4-a716-446655440004 and name eq 'Elite Storage'
Content-Type: application/json


### Get Warehouses ordered by name in descending order using Query Parameters $orderby
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$orderby=name desc
Content-Type: application/json


### Get top 5 Warehouses using Query Parameters $top
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$top=5
Content-Type: application/json


### Get Warehouses with pagination using Query Parameters $top and $skip
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$top=5&$skip=2
Content-Type: application/json


### Get Warehouses with pagination and total count using Query Parameters $top, $skip, and $count
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$top=5&$skip=2&$count=true
Content-Type: application/json


### Get Warehouses after defining paging on service cds file or on package.json file
GET http://localhost:4004/odata/v4/warehouse/Warehouses
Content-Type: application/json


### Get Warehouses after defining paging on service cds file or on package.json file
GET http://localhost:4004/odata/v4/warehouse/Warehouses?$top=12
Content-Type: application/json