### GET call to Read all the Warehouses
GET http://localhost:4004/odata/v4/warehouse/Warehouses


### GET call to Read a specific Warehouse by ID
GET http://localhost:4004/odata/v4/warehouse/Warehouses(550e8400-e29b-41d4-a716-446655440004)


### POST call to Create a new Warehouse
POST http://localhost:4004/odata/v4/warehouse/Warehouses
Content-Type: application/json

{
    "ID": "550e8400-e29b-41d4-a716-446655440010",
    "name" : "Elite Storage",
    "owner" : "Elite Transport Co",
    "address" : "77 Business Zone Panchkula"
}


### PUT call to Update the Warehouse details
PUT http://localhost:4004/odata/v4/warehouse/Warehouses(550e8400-e29b-41d4-a716-446655440010)
Content-Type: application/json

{
    "name" : "Elite Storage New",
    "owner" : "Elite Transport Co Ltd",
    "address" : "601 Business Zone Panchkula"
}


### PATCH call to Update the Warehouse address
PATCH http://localhost:4004/odata/v4/warehouse/Warehouses(550e8400-e29b-41d4-a716-446655440010)
Content-Type: application/json

{
    "address": "605 Business Zone Panchkula"
}



### DELETE call to Remove the Warehouse
DELETE http://localhost:4004/odata/v4/warehouse/Warehouses(550e8400-e29b-41d4-a716-446655440010)