### GET call to Read all the Warehouses
GET http://localhost:4004/odata/v4/warehouse/Warehouses

### POST call to Create a new Warehouse
POST http://localhost:4004/odata/v4/warehouse/Warehouses
Content-Type: application/json

{
    "name" : "Elite Storage",
    "owner" : "Elite Transport Co",
    "address" : "77 Business Zone Panchkula",
    "region_ID" : "550e8400-e29b-41d4-a716-446655440005"
}